batch_size: 128
num_samples: 5000

latent_features: 32

learning_rate: 0.001
num_epochs: 10
lambda_rec: 1.0
lambda_kl: 0.001 # ưu tiên reconstruction loss hơn

lambda_ssim: 0.84

# Quá trình tìm kiếm đã hoàn tất!
# Giá trị Validation Loss tốt nhất đạt được: 0.0082
# Bộ tham số hoàn hảo nhất là:
#     lambda_rec: 0.4961493261011122
#     lambda_kl: 0.0015276491877493211
#     lambda_ssim: 0.7069747270146195

dataset: "CIFAR10"
in_channels: 3